name: Deploy to aws ec2
on: 
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
        
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm run build --prod
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
            key: ${{ secrets.SSH_PRIVATE_KEY }} 
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/var/www/html/dist/

    