name: analizer

on:
  push:
    branches: [master]
jobs:
  build:
    name: Build 
    runs-on: dev
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
       # run: echo Hello, world
        run: ./1.ps1
        shell: pwsh
        

