name: analizer

on:
  push:
    branches: [master]
jobs:
  build:
    name: Build 
    runs-on: dev
    steps:
      - uses: actions/checkout@v1
      - name: Script
        run: .\1.ps1
        shell: powershell

