name: analizer

on:
  push:
    branches: [master]
jobs:
  build:
    name: Build 
    runs-on: dev
    steps:
      - uses: actions/checkout@v2
      #- name: Run a one-line script
       # run: echo Hello, world
      - name: Perform a Pester test from the Tests.ps1 file
        run: |
          cd C:\Program Files\UiPath\Studio
          ls
          pwd
        shell: pwsh

