name: analizer

on:
  push:
    branches: [master]
jobs:
  build:
    name: Build 
    runs-on: dev
    steps:
      - uses: actions/checkout@v3
      - name: Script
        run: |
          cmd cd C:\Users\Rahul Kumar\Pictures\min-project
          cmd ls
          cmd pwd
       

